services:
  backend:
    image: ${ACR_LOGIN_SERVER}/taskmanager-backend:latest
    container_name: taskmanager-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=azure
      - SQL_CONNECTION_STRING=${SQL_CONNECTION_STRING}
      - SQL_ADMIN_USER=${SQL_ADMIN_USER}
      - SQL_ADMIN_PASSWORD=${SQL_ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=86400000
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,https://${VM_PUBLIC_IP}
      - FRONTEND_URL=http://${VM_PUBLIC_IP}
      - SPRING_DATASOURCE_URL=${SQL_CONNECTION_STRING}
      - SPRING_DATASOURCE_USERNAME=${SQL_ADMIN_USER}
      - SPRING_DATASOURCE_PASSWORD=${SQL_ADMIN_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.SQLServerDialect
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - taskmanager-network

  frontend:
    image: ${ACR_LOGIN_SERVER}/taskmanager-frontend:latest
    container_name: taskmanager-frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_API_URL=http://${VM_PUBLIC_IP}:8081/api
      - REACT_APP_ENVIRONMENT=production
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - taskmanager-network

networks:
  taskmanager-network:
    driver: bridge
    name: taskmanager-network

volumes:
  taskmanager-data:
    driver: local